# pubspec.yaml
name: measures_converter
description: A simple Flutter measures converter (metric ↔ imperial).
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
version: 1.0.0+1
